services:
  # DB Service
  db:
    image: postgres:16
    container_name: exceed-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prolific
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - exceed-prolific-network

  # LLM Service
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: exceed-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/var/lib/ollama
      - ./ollama/entrypoint.sh:/entrypoints/entrypoint.sh:ro
    entrypoint: [ "/bin/sh", "/entrypoints/entrypoint.sh" ]
    healthcheck:
      test: [ "CMD", "sh", "-c", "ollama list | grep -q 'llama3.1:8b'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - exceed-prolific-network

  # FastAPI Backend Service
  backend:
    build:
      context:
        ./exceed-prolific-backend
    container_name: exceed-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/prolific
      - OLLAMA_URL=http://ollama:11434
      - PROLIFIC_FRONTEND_URL=http://localhost:3000
    depends_on:
      ollama:
        condition: service_healthy
      db:
        condition: service_started
    networks:
      - exceed-prolific-network

  # NextJS Frontend Service
  frontend:
    build:
      context: ./exceed-prolific-frontend
      args:
        NEXT_PUBLIC_BACKEND_HOST: http://localhost:8000
    container_name: exceed-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=http://localhost:8000
    depends_on:
      - backend
    networks:
      - exceed-prolific-network

networks:
  exceed-prolific-network:
    driver: bridge

volumes:
  db_data: { }
  ollama_data: { }
